<?xml version="1.0" encoding="utf-8"?><Database Name="benDover" Class="Data_AllTablesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=10.1.10.114,1434;Initial Catalog=benDover;Persist Security Info=True;User ID=ugoadmin" SettingsObjectName="Neo_Alfred.Properties.Settings" SettingsPropertyName="benDoverConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Customer" Member="Customers">
    <Type Name="Customer">
      <Column Name="CustID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CustName" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="CustStatus" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="JoinDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Birthday" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="Customer_theORDER" Member="theORDERs" ThisKey="CustID" OtherKey="CustID" Type="theORDER" />
    </Type>
  </Table>
  <Table Name="dbo.theORDER" Member="theORDERs">
    <Type Name="theORDER">
      <Column Name="OrderID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="invoiceNo" Type="System.Decimal" DbType="Decimal(5,0)" CanBeNull="true" />
      <Column Name="oTimeStamp" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="oStatus" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="PayInfo" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Subtotal" Type="System.Decimal" DbType="Decimal(8,0)" CanBeNull="true" />
      <Column Name="Total" Type="System.Decimal" DbType="Decimal(8,0) NOT NULL" CanBeNull="false" />
      <Column Name="BasketSize" Type="System.Decimal" DbType="Decimal(5,0) NOT NULL" CanBeNull="false" />
      <Column Name="CustID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="OrderListID" Type="System.Decimal" DbType="Decimal(6,0) NOT NULL" CanBeNull="false" />
      <Association Name="Customer_theORDER" Member="Customer" ThisKey="CustID" OtherKey="CustID" Type="Customer" IsForeignKey="true" />
    </Type>
  </Table>
</Database>